[package]
name = "ex09"
version = "0.1.0"
authors = ["永野 文崇 <tomotaka.nagano@exmotion.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "*"
regex = "*"
rand = "*"